services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prometheus
    restart: unless-stopped
    ports: 
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
volumes:
  prom_data:
